### ISSUE TITLE
compiling error when using cargo install

### ISSUE THREAD

**Issue by leonhd** [guillemborrell/dr#1]
os: 
=========
windows 10 pro x64, 21h2
+++++++++

rust toolchain:
=========
C:\Users\Leonhard>cargo --version
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

C:\Users\Leonhard>rustc --version
rustc 1.70.0 (90c541806 2023-05-31)

C:\Users\Leonhard>rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
++++++++++

when using "cargo install dr", error info:
==========
.....
   Compiling polars-arrow v0.27.2
   Compiling polars-core v0.27.2
   Compiling polars-arrow v0.26.1
   Compiling polars-core v0.26.1
   Compiling polars-ops v0.27.2
   Compiling polars-time v0.27.2
   Compiling polars-io v0.27.2
   Compiling polars-ops v0.26.1
   Compiling polars-plan v0.27.2
   Compiling polars-time v0.26.1
   Compiling polars-io v0.26.1
   Compiling polars-pipe v0.27.2
   Compiling polars-plan v0.26.1
   Compiling polars-lazy v0.27.2
   Compiling polars-pipe v0.26.1
   Compiling polars-lazy v0.26.1
   Compiling polars-sql v0.2.3
   Compiling dr v0.6.1
error[E0308]: mismatched types
  --> C:\Users\Leonhard\.cargo\registry\src\index.crates.io-6f17d22bba15001f\dr-0.6.1\src\sql.rs:6:30
   |
6  |     context.register("this", ldf);
   |             --------         ^^^ expected `polars_lazy::frame::LazyFrame`, found a different `polars_lazy::frame::LazyFrame`
   |             |
   |             arguments to this method are incorrect
   |
   = note: `polars_lazy::frame::LazyFrame` and `polars_lazy::frame::LazyFrame` have similar names, but are actually distinct types
note: `polars_lazy::frame::LazyFrame` is defined in crate `polars_lazy`
  --> C:\Users\Leonhard\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-lazy-0.26.1\src\frame\mod.rs:70:1
   |
70 | pub struct LazyFrame {
   | ^^^^^^^^^^^^^^^^^^^^
note: `polars_lazy::frame::LazyFrame` is defined in crate `polars_lazy`
  --> C:\Users\Leonhard\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-lazy-0.27.2\src\frame\mod.rs:70:1
   |
70 | pub struct LazyFrame {
   | ^^^^^^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `polars_lazy` are being used?
note: method defined here
  --> C:\Users\Leonhard\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-sql-0.2.3\src\context.rs:40:12
   |
40 |     pub fn register(&mut self, name: &str, lf: LazyFrame) {
   |            ^^^^^^^^

error[E0308]: mismatched types
  --> C:\Users\Leonhard\.cargo\registry\src\index.crates.io-6f17d22bba15001f\dr-0.6.1\src\sql.rs:7:5
   |
4  |   pub fn execute(ldf: LazyFrame, statement: &String) -> LazyFrame {
   |                                                         --------- expected `polars_lazy::frame::LazyFrame` because of return type
...
7  | /     context
8  | |         .execute(statement)
9  | |         .expect("Could not execute statement")
   | |______________________________________________^ expected `polars_lazy::frame::LazyFrame`, found a different `polars_lazy::frame::LazyFrame`
   |
   = note: `polars_lazy::frame::LazyFrame` and `polars_lazy::frame::LazyFrame` have similar names, but are actually distinct types
note: `polars_lazy::frame::LazyFrame` is defined in crate `polars_lazy`
  --> C:\Users\Leonhard\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-lazy-0.27.2\src\frame\mod.rs:70:1
   |
70 | pub struct LazyFrame {
   | ^^^^^^^^^^^^^^^^^^^^
note: `polars_lazy::frame::LazyFrame` is defined in crate `polars_lazy`
  --> C:\Users\Leonhard\.cargo\registry\src\index.crates.io-6f17d22bba15001f\polars-lazy-0.26.1\src\frame\mod.rs:70:1
   |
70 | pub struct LazyFrame {
   | ^^^^^^^^^^^^^^^^^^^^
   = note: perhaps two different versions of crate `polars_lazy` are being used?

For more information about this error, try `rustc --explain E0308`.
error: could not compile `dr` (bin "dr") due to 2 previous errors
error: failed to compile `dr v0.6.1`, intermediate artifacts can be found at `R:\Temp\cargo-installSGJ9Oo`
++++++++++

**Comment by guillemborrell** [comment]
Hi @leonhd !

Thanks for reachig out. I've just published version 0.7 that seems to fix the build. Can you please try and close the issue if the build is successful?

**Comment by leonhd** [comment]
> Hi @leonhd !
> 
> Thanks for reachig out. I've just published version 0.7 that seems to fix the build. Can you please try and close the issue if the build is successful?

This time it builds successfully. Thanks a lot!
